### PR TITLE
Update dark mode background color

### PR DESCRIPTION
**Pull request by Excellent-coding**
https://linear.app/find-labs/issue/ENG-40/update-dark-mode-background-color

### CODE REVIEW

**Comment by khalil-omer** [comment]
@Excellent-coding this PR breaks dark mode. Now I only see light mode.

**Review by khalil-omer — CHANGES_REQUESTED** [review]
Breaks dark mode

**Comment by Excellent-coding** [comment]
I tried with several browsers, but dark mode is working
https://prnt.sc/fRJYQ-uhKJr-
https://prnt.sc/OFIvhHK-uH9d

**Comment by khalil-omer** [comment]
> I tried with several browsers, but dark mode is working https://prnt.sc/fRJYQ-uhKJr- https://prnt.sc/OFIvhHK-uH9d

@Excellent-coding but it is not defaulting correctly based on the user's selected browser prefers-color-scheme preference

**Review by khalil-omer — APPROVED** [review]

**Pull request merged**
