### PR TITLE
Update some dark mode styles to match the designs

### PR DESCRIPTION
**Pull request by Excellent-coding**
https://linear.app/find-labs/issue/ENG-52/update-some-dark-mode-styles-to-match-the-designs

### CODE REVIEW

**Review by khalil-omer — CHANGES_REQUESTED** [review]
"We'll email you a magic link" wrong bg color in dark mode  (system mode) https://cln.sh/l8OUMNHgNcZubAGnAVMS

**Comment by khalil-omer** [comment]
@Excellent-coding reminder about this

**Comment by Excellent-coding** [comment]
> @Excellent-coding reminder about this

Fixed it. Sorry for being unaware of comment

**Comment by Excellent-coding** [comment]
> @Excellent-coding reminder about this

Fixed now. Sorry for being unaware of comment on the github

**Comment by khalil-omer** [comment]
@Excellent-coding there is a build error in Vercel: https://cln.sh/obp82bQmRmYluWM5oTij

**Comment by Excellent-coding** [comment]
> @Excellent-coding there is a build error in Vercel: https://cln.sh/obp82bQmRmYluWM5oTij

Fixed

**Review by khalil-omer — APPROVED** [review]

**Pull request merged**
